import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import Header from "@/components/header";
import Tabel from '@/components/tabel';
import Use from '@/components/use';
import Select from '@/components/select';
import Pagi from '@/components/pagi';
import List from '@/components/list';
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body>
        <Providers>
        <Header/>
         <Use/>
        {children}
        <Tabel/>
        <Select/>
        <Pagi/>
        <List/>
        </Providers>
        </body>
    </html>
  )
}
